default:
	@just --list


# this adds all files to be tracked by git 
rebuild-pre: update-secrets
	@git add --intent-to-add .
# rebuild-post: check-sops


update:
	nix flake update
update-secrets:
	nix flake update mysecrets --timeout 5
