default:
	@just --list


## nixos

# this adds all files to be tracked by git 
# rebuild-pre: update-secrets
# 	@git add --intent-to-add .
# rebuild-post: check-sops
generations:
	sudo nix-env --list-generations --profile /nix/var/nix/profiles/system
generations-hm:
	home-manager generations

update:
	nix flake update
update-secrets:
	nix flake update mysecrets --timeout 5

## tailscale
tailscale-setup:
	sudo tailscale up
tailscale-exit-node:
	sudo tailscale set --advertise-exit-node
